FROM mcr.microsoft.com/playwright:v1.48.2-focal

ENV APP_HOME "/usr/src/app"
WORKDIR ${APP_HOME}

RUN apt-get update \
    && apt-get install -y make \
    && apt-get install -y g++ \
    && apt-get install -y python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY package.json package-lock.json ./

RUN npm ci --legacy-peer-deps

COPY e2e ./e2e

CMD ["npx", "playwright", "test", "--config=e2e/playwright.config.js"]
