services:
  web:
    build:
      context: .
      args:
        prunedev: 'false'
    volumes:
      - './localdata:/usr/src/app/localdata'
    depends_on:
      - redis1
      - redis2
      - statsd
